version: "3.9"

services:
  # me-app:
  # image: ${docker-registry}/me-app:0.1
  # ports:
  # - 3000:3000

  me-app:
    image: babu12f/me-app:0.1
    container_name: me-app
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_started

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=my-db
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express-ui
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      mongodb:
        condition: service_started

volumes:
  mongo-data:
    driver: local
